/**
 * Generated by tool-forge
 * Tool: json-validator
 * Description: Validates JSON strings and returns detailed error information if invalid
 * Timestamp: 2026-01-01T00:00:00.000Z
 */
import { tool } from "@opencode-ai/plugin"
import { asToolResult } from "./tutor/runtime"

export default tool({
  description: "Validates JSON strings and returns detailed error information if invalid",
  args: {
    json: tool.schema.string().describe('JSON string to validate'),
    strict: tool.schema.boolean().optional().describe('Enable strict validation mode'),
  },
  /**
   * Execute function - implements the tool's core logic
   * Returns: Result of the logic expression
   */
  async execute(args) {
    try {
      const parsed = JSON.parse(args.json);
      return asToolResult({ valid: true, data: parsed, message: 'Valid JSON', error: null });
    } catch (error) {
      const errorMsg = error instanceof Error ? error.message : String(error);
      return asToolResult({ valid: false, data: null, message: 'Invalid JSON', error: errorMsg });
    }
  },
})
